# Generated by Django 3.2.13 on 2023-07-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_auto_20230701_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
