# Generated by Django 3.2.13 on 2023-03-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Stock_Symbol', models.TextField()),
                ('LTP', models.FloatField()),
                ('LPT_Date', models.DateField(auto_now_add=True)),
                ('Sell_Initiate', models.FloatField()),
                ('Sell_Target', models.FloatField()),
                ('Buy_Initiate', models.FloatField()),
                ('Buy_Target', models.FloatField()),
            ],
        ),
    ]
