# Generated by Django 3.2.13 on 2023-04-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlymodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Strategy_Name', models.TextField()),
                ('Strategy_Owner', models.TextField()),
                ('Date_Created', models.DateField(auto_now_add=True)),
                ('Strategy_Type', models.TextField()),
                ('Mini_Capital', models.TextField()),
                ('Expected_Returns', models.TextField()),
                ('Fees', models.TextField()),
                ('Cap_Lock_Period', models.TextField()),
            ],
        ),
    ]
