# Generated by Django 3.2.13 on 2023-04-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlymodel', '0003_auto_20230415_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydatamodel',
            name='Market_Type',
            field=models.TextField(default='USA'),
        ),
    ]
