# Generated by Django 3.2.13 on 2023-04-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlymodel', '0004_monthlydatamodel_market_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydatamodel',
            name='LTP',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
