# Generated by Django 3.2.13 on 2023-04-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlymodel', '0005_alter_monthlydatamodel_ltp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydatamodel',
            name='Market_Type',
            field=models.TextField(blank=True, default='USA', null=True),
        ),
    ]
