# Generated by Django 3.2.13 on 2023-04-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlymodel', '0006_alter_monthlydatamodel_market_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydatamodel',
            name='Market_Type',
            field=models.TextField(default='USA'),
        ),
    ]
