# Generated by Django 3.2.13 on 2023-04-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlymodel', '0007_alter_monthlydatamodel_market_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Broker_name', models.TextField()),
                ('Cust_Id', models.TextField()),
                ('API_Key', models.TextField(null=True)),
                ('API_Secret', models.TextField(null=True)),
                ('Username', models.TextField(null=True)),
                ('Password', models.TextField(null=True)),
                ('Market_Types', models.TextField(null=True)),
            ],
        ),
    ]
