# Generated by Django 3.2.13 on 2023-04-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlymodel', '0008_brokermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStrategyMappingModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Month_Data_Model_id', models.TextField()),
                ('Strategy_id', models.TextField()),
            ],
        ),
    ]
