# Generated by Django 3.2.13 on 2023-06-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlymodel', '0009_datastrategymappingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Stock_Symbol', models.TextField()),
                ('LPT_Date', models.DateField(auto_now_add=True)),
                ('Buy_Initiate', models.FloatField()),
                ('Buy_Target', models.FloatField()),
                ('Buy_Initiate_Flag', models.BooleanField(default=True)),
                ('Buy_Target_Flag', models.BooleanField(default=False)),
            ],
        ),
    ]
