# Generated by Django 3.2.13 on 2023-06-30 18:44

import db_file_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlymodel', '0010_alertdatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionalDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.FileField(storage=db_file_storage.storage.DatabaseFileStorage(), upload_to='')),
                ('Market_Type', models.TextField()),
                ('Header', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
