# Generated by Django 3.2.13 on 2023-06-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlymodel', '0010_alertdatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionalDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.BinaryField(null=True)),
                ('Market_Type', models.TextField()),
                ('Header', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
