# Generated by Django 3.2.13 on 2023-07-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlymodel', '0011_positionaldatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionaldatamodel',
            name='Image',
            field=models.TextField(),
        ),
    ]
