# Generated by Django 3.2.13 on 2023-07-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlymodel', '0012_alter_positionaldatamodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField()),
                ('Body', models.TextField()),
                ('Date_Added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
