# Generated by Django 3.2.13 on 2023-07-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlymodel', '0013_blogpostdatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostdatamodel',
            name='URL_Slug',
            field=models.TextField(default='demo'),
            preserve_default=False,
        ),
    ]
