# Generated by Django 3.2.13 on 2023-07-29 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monthlymodel', '0014_blogpostdatamodel_url_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStrategySubscribe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Added', models.DateField(auto_now_add=True)),
                ('Strategy_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monthlymodel.strategymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
