# Generated by Django 3.2.13 on 2023-07-29 19:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monthlymodel', '0015_userstrategysubscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStrategySubscribe',
            new_name='UserStrategySubscribeModel',
        ),
    ]
